-- DCX Predictor — full schema. Paste into Supabase SQL editor and run once.
-- Implements SPEC.md invariants I1–I7. Idempotent-ish: drops views/functions first.

-- ---------------------------------------------------------------- tables

create table if not exists players (
  id   smallint generated by default as identity primary key,
  name text not null unique
);

create table if not exists matches (
  id           bigint primary key,          -- football-data.org match id
  matchday     int,
  stage        text not null,               -- GROUP_STAGE / LAST_32 / ... / FINAL
  grp          text,                        -- GROUP_A..GROUP_L (null in knockouts)
  kickoff_utc  timestamptz not null,
  status       text not null default 'TIMED',
  home_team    text,
  home_tla     text,
  home_crest   text,
  away_team    text,
  away_tla     text,
  away_crest   text,
  home_score   int,                         -- 90-minute (regulation) score
  away_score   int,
  last_synced  timestamptz not null default now()
);

create table if not exists predictions (
  id         bigint generated by default as identity primary key,
  player_id  smallint not null references players (id),
  match_id   bigint not null references matches (id),
  home_pred  int not null check (home_pred between 0 and 20),
  away_pred  int not null check (away_pred between 0 and 20),
  updated_at timestamptz not null default now(),
  unique (player_id, match_id)              -- I1
);

create table if not exists bonus_picks (
  player_id    smallint primary key references players (id),
  champion     text,
  golden_boot  text,
  bafana_stage text check (bafana_stage in
    ('GROUP','LAST_32','LAST_16','QUARTER_FINALS','SEMI_FINALS','RUNNER_UP','CHAMPIONS')),
  updated_at   timestamptz not null default now()
);

-- single row, filled by admin after the final
create table if not exists bonus_results (
  id           boolean primary key default true check (id),
  champion     text,
  golden_boot  text,
  bafana_stage text
);

create index if not exists idx_predictions_match on predictions (match_id);
create index if not exists idx_matches_kickoff on matches (kickoff_utc);

-- ---------------------------------------------------------------- seed players

insert into players (name) values
  ('Marthelize'), ('Garsen'), ('Lewella'), ('Keiketlile'),
  ('Vuyo'), ('Magonna'), ('Thulani'), ('Ramalau'), ('Zayaan')
on conflict (name) do nothing;

-- ---------------------------------------------------------------- scoring views (I4)
-- Views run with owner privileges by design: they expose only aggregates/points,
-- never pre-kickoff predicted scores.

drop view if exists leaderboard;
drop view if exists match_points;

create view match_points as
select
  p.player_id,
  p.match_id,
  m.stage,
  m.status,
  case when m.status = 'FINISHED' and m.home_score is not null then
    (case
       when p.home_pred = m.home_score and p.away_pred = m.away_score then 3
       when sign(p.home_pred - p.away_pred) = sign(m.home_score - m.away_score) then 1
       else 0
     end)
    * (case when m.stage = 'GROUP_STAGE' then 1 else 2 end)
  end as points,
  (m.status = 'FINISHED' and m.home_score is not null
   and p.home_pred = m.home_score and p.away_pred = m.away_score) as exact
from predictions p
join matches m on m.id = p.match_id;

create view leaderboard as
with mp as (
  select player_id,
         coalesce(sum(points), 0)                            as match_pts,
         count(*) filter (where exact)                       as exacts,
         count(*) filter (where not exact and points > 0)    as outcomes
  from match_points
  group by player_id
),
bp as (
  select b.player_id,
         case when r.champion is not null and b.champion = r.champion then 10 else 0 end
       + case when r.golden_boot is not null and b.golden_boot is not null
              and lower(trim(b.golden_boot)) = lower(trim(r.golden_boot)) then 5 else 0 end
       + case when r.bafana_stage is not null and b.bafana_stage = r.bafana_stage then 5 else 0 end
         as bonus_pts
  from bonus_picks b
  left join bonus_results r on true
)
select
  pl.id   as player_id,
  pl.name,
  coalesce(mp.match_pts, 0) + coalesce(bp.bonus_pts, 0) as points,
  coalesce(mp.match_pts, 0)  as match_pts,
  coalesce(bp.bonus_pts, 0)  as bonus_pts,
  coalesce(mp.exacts, 0)     as exacts,
  coalesce(mp.outcomes, 0)   as outcomes
from players pl
left join mp on mp.player_id = pl.id
left join bp on bp.player_id = pl.id
-- only players who are actually playing: at least one pick (match or bonus)
where exists (select 1 from predictions pr where pr.player_id = pl.id)
   or exists (select 1 from bonus_picks bo where bo.player_id = pl.id)
order by points desc, exacts desc, outcomes desc, pl.name;

-- ---------------------------------------------------------------- RLS (I2, I3)

alter table players       enable row level security;
alter table matches       enable row level security;
alter table predictions   enable row level security;
alter table bonus_picks   enable row level security;
alter table bonus_results enable row level security;

drop policy if exists players_read       on players;
drop policy if exists matches_read       on matches;
drop policy if exists predictions_read   on predictions;
drop policy if exists bonus_picks_read   on bonus_picks;
drop policy if exists bonus_results_read on bonus_results;

create policy players_read on players for select using (true);
create policy matches_read on matches for select using (true);

-- picks become visible to everyone only once the match has kicked off (I3)
create policy predictions_read on predictions for select
  using (exists (select 1 from matches m
                 where m.id = match_id and m.kickoff_utc <= now()));

-- bonus picks visible to everyone only once locked (first LAST_32 kickoff)
create policy bonus_picks_read on bonus_picks for select
  using ((select min(kickoff_utc) from matches where stage = 'LAST_32') <= now());

create policy bonus_results_read on bonus_results for select using (true);

-- No insert/update/delete policies for anon: all writes go through the RPCs below
-- (service_role bypasses RLS for sync and admin backfill).

-- ---------------------------------------------------------------- RPCs (I2, I7, C1–C3)

create or replace function save_pick(p_player smallint, p_match bigint, p_home int, p_away int)
returns void
language plpgsql security definer set search_path = public as $$
begin
  if p_home is null or p_away is null
     or p_home not between 0 and 20 or p_away not between 0 and 20 then
    raise exception 'INVALID_SCORE';
  end if;
  if not exists (select 1 from matches where id = p_match and kickoff_utc > now()) then
    raise exception 'PICKS_LOCKED';
  end if;
  insert into predictions (player_id, match_id, home_pred, away_pred)
  values (p_player, p_match, p_home, p_away)
  on conflict (player_id, match_id) do update
    set home_pred = excluded.home_pred,
        away_pred = excluded.away_pred,
        updated_at = now();
end $$;

-- a player's own picks regardless of kickoff (identity is the selected name — SD-01)
create or replace function my_picks(p_player smallint)
returns table (match_id bigint, home_pred int, away_pred int)
language sql security definer set search_path = public as $$
  select match_id, home_pred, away_pred from predictions where player_id = p_player;
$$;

create or replace function save_bonus(p_player smallint, p_champion text, p_boot text, p_bafana text)
returns void
language plpgsql security definer set search_path = public as $$
begin
  if (select min(kickoff_utc) from matches where stage = 'LAST_32') <= now() then
    raise exception 'BONUS_LOCKED';
  end if;
  if p_bafana is not null and p_bafana not in
     ('GROUP','LAST_32','LAST_16','QUARTER_FINALS','SEMI_FINALS','RUNNER_UP','CHAMPIONS') then
    raise exception 'INVALID_STAGE';
  end if;
  insert into bonus_picks (player_id, champion, golden_boot, bafana_stage)
  values (p_player, p_champion, left(p_boot, 60), p_bafana)
  on conflict (player_id) do update
    set champion = excluded.champion,
        golden_boot = excluded.golden_boot,
        bafana_stage = excluded.bafana_stage,
        updated_at = now();
end $$;

create or replace function my_bonus(p_player smallint)
returns table (champion text, golden_boot text, bafana_stage text)
language sql security definer set search_path = public as $$
  select champion, golden_boot, bafana_stage from bonus_picks where player_id = p_player;
$$;
